### ISSUE TITLE
Add New Column in Cassandra for Notification Failure Reason

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/dao#17]
Currently, we are not storing the reasons for notification failures in Cassandra. Therefore, it is necessary to create a new column in Cassandra specifically designed for saving the notification failure reasons.

**Comment by karntrehan** [comment]
Dev done. Testing locally.

**Comment by pankajjangid05** [comment]
Changes are done and tested locally. @chinmoy12c Please review this PR's: https://github.com/samagra-comms/dao/pull/19

**Comment by geeky-abhishek** [comment]
PR is raised. @chinmoy12c to review the PR

**Comment by pankajjangid05** [comment]
@chinmoy12c Please also review this PR: 

- [Message Rosa](https://github.com/samagra-comms/message-rosa/pull/30)

**Comment by geeky-abhishek** [comment]
Under review @chinmoy12c

**Comment by pankajjangid05** [comment]
The code is deployed on staging. Today I will test it on the staging.
