### ISSUE TITLE
[Doc] - Documentation for Database Schema

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/dao#18]
We require comprehensive documentation for the Cassandra and PostgreSQL database schemas.

**Comment by pankajjangid05** [comment]
**Databases Used by UCI:**

- [x] Cassandra (DB - Xmessage) -  Used to archive bot conversation history.
- [x] Postgres (DB - formsdb) - Stores questions and user-associated answers.
- [x] Postgres (DB - user_analytics) - Manages delivery reports for notifications.
- [x] Postgres (DB - comms) - Houses essential bot data, including Adapter, Transformer, Conversation logic, User Segment, and related information.

**Comment by aakashyadav-kgp** [comment]
WIP. Planning to close this today.

**Comment by pankajjangid05** [comment]
Hey @chinmoy12c 

Please review this PR : https://github.com/samagra-comms/community/pull/70

**Comment by chinmoy12c** [comment]
Changes to be integrated according to review.

**Comment by pankajjangid05** [comment]
This is merged with the main branch so we can close this ticket. 

Document URL : https://uci.sunbird.org/use/developer/database-schema
